name: Dependabot auto-merge
on: 
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: |
          (
            steps.metadata.outputs.dependency-type == 'direct:development' &&
            steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.metadata.outputs.dependency-type == 'direct:production' &&
            steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.metadata.outputs.dependency-type == 'indirect' &&
            steps.metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.metadata.outputs.dependency-type == 'direct:development' &&
            steps.metadata.outputs.update-type == 'version-update:semver-minor' &&
            startsWith(steps.metadata.outputs.previous-version, '0.') == false
          )
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
